fix(site): Fix a few React warnings (#76)
* Fix missing key prop

```
Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at Typography (/Users/ak/-/projects/hash/github/blockprotocol/node_modules/@mui/material/node/Typography/Typography.js:108:49)
    at InfoCard (webpack-internal:///./src/components/InfoCard/InfoCard.tsx:30:3)
    at /Users/ak/-/projects/hash/github/blockprotocol/node_modules/@mdx-js/react/dist/cjs.js:153:30
    at div
    at /Users/ak/-/projects/hash/github/blockprotocol/node_modules/@emotion/react/dist/emotion-element-c24e4fdd.cjs.dev.js:51:25
    at Box (/Users/ak/-/projects/hash/github/blockprotocol/node_modules/@mui/system/createBox.js:42:41)
    at div
    at /Users/ak/-/projects/hash/github/blockprotocol/node_modules/@emotion/react/dist/emotion-element-c24e4fdd.cjs.dev.js:51:25
    at Box (/Users/ak/-/projects/hash/github/blockprotocol/node_modules/@mui/system/createBox.js:42:41)
    at InfoCardWrapper (webpack-internal:///./src/components/InfoCard/InfoCardWrapper.tsx:16:3)
    at /Users/ak/-/projects/hash/github/blockprotocol/node_modules/@mdx-js/react/dist/cjs.js:153:30
    at wrapper (/Users/ak/-/projects/hash/github/blockprotocol/node_modules/@mdx-js/react/dist/cjs.js:148:25)
    at /Users/ak/-/projects/hash/github/blockprotocol/node_modules/@mdx-js/react/dist/cjs.js:153:30
```

* Replace `:first-child` with `:first-of-type`

```
The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type".
```

* Prevent `p` → `p` nesting

```
Warning: validateDOMNesting(...): <ul> cannot appear as a descendant of <p>.
    at ul
    at eval (webpack-internal:///../node_modules/@emotion/react/dist/emotion-element-699e6908.browser.esm.js:53:73)
    at Box (webpack-internal:///../node_modules/@mui/system/esm/createBox.js:33:76)
    at ul
    at eval (webpack-internal:///../node_modules/@mdx-js/react/dist/esm.js:153:30)
```

* Defer loading fontawesome

```
Warning: Expected server HTML to contain a matching <span> in <a>.
```

* Fix duplicate key

```
Warning: Encountered two children with the same key, ListItem. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

* Fix svg height

```
Error: <svg> attribute height: Expected length, "auto".
```

* Fix className mismatch

```
Warning: Prop `className` did not match. Server: "MuiSvgIcon-root MuiSvgIcon-fontSizeMedium css-13b04xk-MuiSvgIcon-root" Client: "MuiSvgIcon-root MuiSvgIcon-fontSizeMedium css-1ihsezv-MuiSvgIcon-root"
    at svg
    at eval (webpack-internal:///../node_modules/@emotion/react/dist/emotion-element-699e6908.browser.esm.js:53:73)
    at SvgIcon (webpack-internal:///../node_modules/@mui/material/SvgIcon/SvgIcon.js:82:86)
    at BlockProtocolLogoIcon (webpack-internal:///./src/components/SvgIcon/BlockProtocolLogoIcon.tsx:21:5)
    at a
    at eval (webpack-internal:///../node_modules/@emotion/react/dist/emotion-element-699e6908.browser.esm.js:53:73)
```